
import { Option, RoomFeel, RoomStyle, RoomType, RoomUsage, WorkflowType } from './types';

export const WORKFLOW_TYPE_OPTIONS: Option<WorkflowType>[] = [
  { value: 'full', label: 'Full Makeover', description: 'Completely transform the room (Change fixed parts also).' },
  { value: 'partial', label: 'Partial Makeover', description: 'Update parts of the room while keeping fixed parts as is.' },
  { value: 'match', label: 'Match a Photo', description: 'Redesign to replicate an inspiration image.' },
  { value: 'custom', label: 'Custom Request', description: 'User specifies exactly what they want.' },
];

export const ROOM_TYPE_OPTIONS: Option<RoomType>[] = [
    { value: 'Living Room', label: 'Living Room' },
    { value: 'Primary Bedroom', label: 'Primary Bedroom' },
    { value: 'Kitchen', label: 'Kitchen' },
    { value: 'Dining Room', label: 'Dining Room' },
    { value: 'Home Office', label: 'Home Office' },
    { value: 'Full Bathroom', label: 'Full Bathroom' },
    { value: 'Game Room', label: 'Game Room' },
    { value: 'Walk-in Closet', label: 'Walk-in Closet' },
    { value: 'Content Creator Room', label: 'Content Creator Room' },
    { value: 'Pet Room', label: 'Pet Room' },
];

export const ROOM_USAGE_OPTIONS: Record<RoomType, Option<RoomUsage>[]> = {
  'Living Room': [
    { value: 'Watching TV – wall mounted tv, media console, sofa', label: 'Watching TV – wall mounted tv, media console, sofa' },
    { value: 'Casual conversation – sofa, pair of accent chairs, coffee table', label: 'Casual conversation – sofa, pair of accent chairs, coffee table' },
    { value: 'Hosting guests – sectional sofa, side tables, area rug', label: 'Hosting guests – sectional sofa, side tables, area rug' },
    { value: 'Reading – armchair, floor lamp, side table', label: 'Reading – armchair, floor lamp, side table' },
    { value: 'Listening to music – stereo cabinet, bookshelf speakers, acoustic wall panels', label: 'Listening to music – stereo cabinet, bookshelf speakers, acoustic wall panels' },
    { value: 'Playing board games – game table, four chairs, pendant light', label: 'Playing board games – game table, four chairs, pendant light' },
    { value: 'Kids\' playtime – play rug, toy storage bench, open shelving', label: 'Kids\' playtime – play rug, toy storage bench, open shelving' },
    { value: 'Napping – daybed, blackout curtains, wall sconce', label: 'Napping – daybed, blackout curtains, wall sconce' },
    { value: 'Holiday gatherings – nesting coffee tables, stackable stools, serving console', label: 'Holiday gatherings – nesting coffee tables, stackable stools, serving console' },
    { value: 'Video calls – compact task desk, key light, backdrop panel', label: 'Video calls – compact task desk, key light, backdrop panel' },
  ],
  'Primary Bedroom': [
    { value: 'Sleeping – bed frame with headboard, mattress, nightstands', label: 'Sleeping – bed frame with headboard, mattress, nightstands' },
    { value: 'Dressing – six drawer dresser, wall mirror, bench', label: 'Dressing – six drawer dresser, wall mirror, bench' },
    { value: 'Storing clothes – closet system, adjustable shelving, drawer tower', label: 'Storing clothes – closet system, adjustable shelving, drawer tower' },
    { value: 'Reading in bed – swing arm sconces, upholstered headboard, bedside shelf', label: 'Reading in bed – swing arm sconces, upholstered headboard, bedside shelf' },
    { value: 'Watching TV in bed – wall mounted tv, low media dresser, cable channel cover', label: 'Watching TV in bed – wall mounted tv, low media dresser, cable channel cover' },
    { value: 'Intimacy – dimmable bedside lamps, layered drapery, plush area rug', label: 'Intimacy – dimmable bedside lamps, layered drapery, plush area rug' },
    { value: 'Meditation – floor cushion, accent lamp, small side table', label: 'Meditation – floor cushion, accent lamp, small side table' },
    { value: 'Stretching – mirror wall, storage bench, area rug', label: 'Stretching – mirror wall, storage bench, area rug' },
    { value: 'Applying makeup – vanity table, lighted mirror, vanity stool', label: 'Applying makeup – vanity table, lighted mirror, vanity stool' },
    { value: 'Storing valuables – visible safe cabinet, lockable drawer chest, wall niche door', label: 'Storing valuables – visible safe cabinet, lockable drawer chest, wall niche door' },
  ],
  'Kitchen': [
    { value: 'Cooking – range, vent hood, tiled backsplash', label: 'Cooking – range, vent hood, tiled backsplash' },
    { value: 'Food preparation – island countertop, butcher block board, under cabinet lighting', label: 'Food preparation – island countertop, butcher block board, under cabinet lighting' },
    { value: 'Baking – wall oven, baking sheet storage cabinet, stand mixer', label: 'Baking – wall oven, baking sheet storage cabinet, stand mixer' },
    { value: 'Cold food storage – refrigerator, landing counter, tall pullout pantry', label: 'Cold food storage – refrigerator, landing counter, tall pullout pantry' },
    { value: 'Storing dry goods – pantry cabinet, adjustable shelving, canister set', label: 'Storing dry goods – pantry cabinet, adjustable shelving, canister set' },
    { value: 'Dishwashing – dishwasher, under-mount sink, pull down faucet', label: 'Dishwashing – dishwasher, under-mount sink, pull down faucet' },
    { value: 'Brewing coffee – coffee maker, dedicated counter station, upper shelf', label: 'Brewing coffee – coffee maker, dedicated counter station, upper shelf' },
    { value: 'Eating quick meals – island overhang, counter stools, pendant lights', label: 'Eating quick meals – island overhang, counter stools, pendant lights' },
    { value: 'Packing lunches – container drawer organizer, countertop packing zone, upper cabinet bin', label: 'Packing lunches – container drawer organizer, countertop packing zone, upper cabinet bin' },
    { value: 'Recycling disposal – pullout recycle bin cabinet, matching base cabinet front', label: 'Recycling disposal – pullout recycle bin cabinet, matching base cabinet front' },
  ],
  'Dining Room': [
    { value: 'Sit down meals – dining table, dining chairs, chandelier', label: 'Sit down meals – dining table, dining chairs, chandelier' },
    { value: 'Formal dinners – upholstered dining chairs, dimmable chandelier, sideboard', label: 'Formal dinners – upholstered dining chairs, dimmable chandelier, sideboard' },
    { value: 'Hosting dinner parties – extendable dining table, stackable chairs, sideboard staging surface', label: 'Hosting dinner parties – extendable dining table, stackable chairs, sideboard staging surface' },
    { value: 'Homework – table task lamp, rolling storage cart, chair cushion', label: 'Homework – table task lamp, rolling storage cart, chair cushion' },
    { value: 'Arts and crafts – utility task lamp, rolling storage cart, wipeable table cover', label: 'Arts and crafts – utility task lamp, rolling storage cart, wipeable table cover' },
    { value: 'Puzzle building – puzzle board, adjustable table lamp, storage cabinet', label: 'Puzzle building – puzzle board, adjustable table lamp, storage cabinet' },
    { value: 'Gift wrapping – wrapping cart, ribbon rail, under table bin', label: 'Gift wrapping – wrapping cart, ribbon rail, under table bin' },
    { value: 'Buffet serving – sideboard, serving shelf, warming lamp look fixture', label: 'Buffet serving – sideboard, serving shelf, warming lamp look fixture' },
    { value: 'Playing board games – square game table, four chairs, pendant light', label: 'Playing board games – square game table, four chairs, pendant light' },
    { value: 'Paperwork sorting – lateral file credenza, tiered tray, table lamp', label: 'Paperwork sorting – lateral file credenza, tiered tray, table lamp' },
  ],
  'Full Bathroom': [
    { value: 'Showering – glass shower enclosure, wall niche, shower set', label: 'Showering – glass shower enclosure, wall niche, shower set' },
    { value: 'Bathing – freestanding tub, tub caddy, bath pillow', label: 'Bathing – freestanding tub, tub caddy, bath pillow' },
    { value: 'Using the toilet – toilet, toilet roll holder, small wall shelf', label: 'Using the toilet – toilet, toilet roll holder, small wall shelf' },
    { value: 'Brushing teeth – vanity sink, backlit mirror, countertop organizer', label: 'Brushing teeth – vanity sink, backlit mirror, countertop organizer' },
    { value: 'Handwashing – pedestal sink, soap dispenser, towel ring', label: 'Handwashing – pedestal sink, soap dispenser, towel ring' },
    { value: 'Shaving – magnifying mirror, razor stand, toiletries shelf', label: 'Shaving – magnifying mirror, razor stand, toiletries shelf' },
    { value: 'Applying makeup – lighted mirror, vanity stool, makeup caddy', label: 'Applying makeup – lighted mirror, vanity stool, makeup caddy' },
    { value: 'Hair drying – countertop dryer stand, heat resistant mat, outlet grommet', label: 'Hair drying – countertop dryer stand, heat resistant mat, outlet grommet' },
    { value: 'Medicine storage – lockable medicine cabinet, interior organizer bins, label strip', label: 'Medicine storage – lockable medicine cabinet, interior organizer bins, label strip' },
    { value: 'First aid care – first aid box, shallow wall shelf, labeled bin', label: 'First aid care – first aid box, shallow wall shelf, labeled bin' },
  ],
  'Home Office': [
    { value: 'Computer work – desk, ergonomic chair, monitor arm', label: 'Computer work – desk, ergonomic chair, monitor arm' },
    { value: 'Video conferencing – webcam on monitor, key light, backdrop panel', label: 'Video conferencing – webcam on monitor, key light, backdrop panel' },
    { value: 'Phone calls – handset dock, privacy panel, side table', label: 'Phone calls – handset dock, privacy panel, side table' },
    { value: 'Filing paperwork – lateral file cabinet, file rails, label tabs', label: 'Filing paperwork – lateral file cabinet, file rails, label tabs' },
    { value: 'Printing – printer shelf, paper drawer, cord cover', label: 'Printing – printer shelf, paper drawer, cord cover' },
    { value: 'Scanning – document scanner shelf, output tray, cable cover', label: 'Scanning – document scanner shelf, output tray, cable cover' },
    { value: 'Paying bills – desk blotter, mail sorter, lockable drawer', label: 'Paying bills – desk blotter, mail sorter, lockable drawer' },
    { value: 'Note taking – notebook stand, pen cup, task lamp', label: 'Note taking – notebook stand, pen cup, task lamp' },
    { value: 'Whiteboard planning – wall mounted whiteboard, marker tray, calendar strip', label: 'Whiteboard planning – wall mounted whiteboard, marker tray, calendar strip' },
    { value: 'Charging devices – desktop charging hub, cable tray, desk grommet', label: 'Charging devices – desktop charging hub, cable tray, desk grommet' },
  ],
  'Game Room': [
    { value: 'Video gaming – large tv, media console, gaming sofa', label: 'Video gaming – large tv, media console, gaming sofa' },
    { value: 'Billiards – pool table, cue rack, over table light', label: 'Billiards – pool table, cue rack, over table light' },
    { value: 'Table tennis – ping pong table, paddle rack, overhead light', label: 'Table tennis – ping pong table, paddle rack, overhead light' },
    { value: 'Foosball – foosball table, wall scoreboard, floor rug', label: 'Foosball – foosball table, wall scoreboard, floor rug' },
    { value: 'Air hockey – air hockey table, puck holder, ceiling light', label: 'Air hockey – air hockey table, puck holder, ceiling light' },
    { value: 'Darts – dartboard with surround, toe line marker, scoreboard panel', label: 'Darts – dartboard with surround, toe line marker, scoreboard panel' },
    { value: 'Board games – game table, four chairs, storage credenza', label: 'Board games – game table, four chairs, storage credenza' },
    { value: 'Card games – felt card table, four chairs, chip rack', label: 'Card games – felt card table, four chairs, chip rack' },
    { value: 'Arcade gaming – arcade cabinet, poster lightbox, floor mat', label: 'Arcade gaming – arcade cabinet, poster lightbox, floor mat' },
    { value: 'Pinball – pinball machine, art lightbox, power strip channel', label: 'Pinball – pinball machine, art lightbox, power strip channel' },
  ],
  'Walk-in Closet': [
    { value: 'Hanging clothes storage – double hanging rods, upper shelf, hanger set', label: 'Hanging clothes storage – double hanging rods, upper shelf, hanger set' },
    { value: 'Shoe storage – shoe towers, angled shelves, toe stops', label: 'Shoe storage – shoe towers, angled shelves, toe stops' },
    { value: 'Accessory storage – drawer unit, compartment dividers, shallow trays', label: 'Accessory storage – drawer unit, compartment dividers, shallow trays' },
    { value: 'Dressing – mirror wall, bench, area rug', label: 'Dressing – mirror wall, bench, area rug' },
    { value: 'Outfit planning – valet rod, outfit rail, accessories shelf', label: 'Outfit planning – valet rod, outfit rail, accessories shelf' },
    { value: 'Jewelry storage – jewelry drawer inserts, glass lid, lock', label: 'Jewelry storage – jewelry drawer inserts, glass lid, lock' },
    { value: 'Suitcase storage – overhead shelves, labeled bins, luggage stand', label: 'Suitcase storage – overhead shelves, labeled bins, luggage stand' },
    { value: 'Rotating seasonal clothing – high hanging rod lift, tote bins, label rail', label: 'Rotating seasonal clothing – high hanging rod lift, tote bins, label rail' },
    { value: 'Laundry hamper staging – pullout hamper, divider baskets, floor mat', label: 'Laundry hamper staging – pullout hamper, divider baskets, floor mat' },
    { value: 'Storing valuables in a safe – visible safe cabinet, keypad front, wall niche', label: 'Storing valuables in a safe – visible safe cabinet, keypad front, wall niche' },
  ],
  'Content Creator Room': [
    { value: 'Video filming – camera on tripod, key light, backdrop stand', label: 'Video filming – camera on tripod, key light, backdrop stand' },
    { value: 'Livestreaming – camera, key light, streaming desk with arm mounts', label: 'Livestreaming – camera, key light, streaming desk with arm mounts' },
    { value: 'Podcast recording – microphone boom arm, audio interface, acoustic wall panels', label: 'Podcast recording – microphone boom arm, audio interface, acoustic wall panels' },
    { value: 'Voiceover recording – vocal shield, microphone stand, monitor arm', label: 'Voiceover recording – vocal shield, microphone stand, monitor arm' },
    { value: 'Video editing – editing desk, dual monitors on arms, ergonomic chair', label: 'Video editing – editing desk, dual monitors on arms, ergonomic chair' },
    { value: 'Product photography – lightbox, pair of softboxes, backdrop stand', label: 'Product photography – lightbox, pair of softboxes, backdrop stand' },
    { value: 'Photo editing – calibrated monitor, desk mat, storage drive dock', label: 'Photo editing – calibrated monitor, desk mat, storage drive dock' },
    { value: 'Green screen shooting – collapsible green screen, support stand, floor tape', label: 'Green screen shooting – collapsible green screen, support stand, floor tape' },
    { value: 'Makeup application – vanity mirror lights, stool, organizer caddy', label: 'Makeup application – vanity mirror lights, stool, organizer caddy' },
    { value: 'Prop storage – shelving units, labeled storage bins, pegboard wall', label: 'Prop storage – shelving units, labeled storage bins, pegboard wall' },
  ],
  'Pet Room': [
    { value: 'Feeding pets – raised bowls, feeding mat, scoop hook', label: 'Feeding pets – raised bowls, feeding mat, scoop hook' },
    { value: 'Sleeping on a pet bed – orthopedic pet bed, washable cover, toy basket', label: 'Sleeping on a pet bed – orthopedic pet bed, washable cover, toy basket' },
    { value: 'Litter box use – enclosed litter cabinet, litter mat, deodorizer canister', label: 'Litter box use – enclosed litter cabinet, litter mat, deodorizer canister' },
    { value: 'Potty pad training – pad tray, wipeable floor mat, wall hook rail', label: 'Potty pad training – pad tray, wipeable floor mat, wall hook rail' },
    { value: 'Grooming – grooming table, tool rack, overhead task light', label: 'Grooming – grooming table, tool rack, overhead task light' },
    { value: 'Pet bathing – dog wash tub, handheld sprayer, drying shelf', label: 'Pet bathing – dog wash tub, handheld sprayer, drying shelf' },
    { value: 'Playtime – play mat, toy bin, wall shelf for toys', label: 'Playtime – play mat, toy bin, wall shelf for toys' },
    { value: 'Obedience training – floor markers, treat pouch hook, training stool', label: 'Obedience training – floor markers, treat pouch hook, training stool' },
    { value: 'Storing pet supplies – storage cabinet, labeled bins, shelf risers', label: 'Storing pet supplies – storage cabinet, labeled bins, shelf risers' },
    { value: 'Temporary isolation – crate, crate cover, storage shelf', label: 'Temporary isolation – crate, crate cover, storage shelf' },
  ],
};

export const ROOM_FEEL_OPTIONS: Option<RoomFeel>[] = [
    { value: 'Let AI Decide', label: 'Let AI Decide', description: 'AI chooses the best feel for your style.' },
    { value: 'Relaxed', label: 'Relaxed', description: 'Easygoing, breezy, casual' },
    { value: 'Cozy', label: 'Cozy', description: 'Snug, warm, comforting' },
    { value: 'Bright', label: 'Bright', description: 'Light-filled, fresh, uplifting' },
    { value: 'Elegant', label: 'Elegant', description: 'Graceful, polished, refined' },
    { value: 'Bold', label: 'Bold', description: 'Strong, dramatic, attention-grabbing' },
    { value: 'Playful', label: 'Playful', description: 'Youthful, creative, fun' },
    { value: 'Minimal', label: 'Minimal', description: 'Simple, uncluttered, clean' },
    { value: 'Natural', label: 'Natural', description: 'Earthy, grounded, organic' },
    { value: 'Moody', label: 'Moody', description: 'Dark, intimate, dramatic' },
    { value: 'Classic', label: 'Classic', description: 'Timeless, structured, traditional' },
];

export const ROOM_STYLE_OPTIONS: Option<RoomStyle>[] = [
    { value: 'Modern', label: 'Modern' },
    { value: 'Transitional', label: 'Transitional' },
    { value: 'Contemporary', label: 'Contemporary' },
    { value: 'Scandinavian', label: 'Scandinavian' },
    { value: 'Moroccan', label: 'Moroccan' },
    { value: 'Industrial', label: 'Industrial' },
    { value: 'Mid-Century Modern', label: 'Mid-Century Modern' },
    { value: 'Coastal', label: 'Coastal' },
    { value: 'Japandi', label: 'Japandi' },
    { value: 'Bohemian', label: 'Bohemian' },
];
